name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport

on: [tags]

 jobs:
  build:

     runs-on: ubuntu-latest

     steps:
    - name: Publish
      env:
        PUBLISH_KEY: ${{secrets.PUBLISH_KEY}}
        PUBLISH_SECRET: ${{secrets.PUBLISH_SECRET}}
      run: ./gradlew publishPlugins -Dgradle.publish.key=$PUBLISH_KEY -Dgradle.publish.secret=$PUBLISH_SECRET
